package main

import (
	"context"
	"fmt"
	"strconv"

	"github.com/Johnnydeeps/gator/internal/database"
)

func handlerBrowse(appStatePtr *state, cmd command, user database.User) error {
	// default limit of 2 set here to be pased as an argument to posts.sql queries for reference
	limit := 2
	if len(cmd.UserArgs) > 0 {
		// need to convert the string number from the cli to an integer that is useable in the program.
		// strconv.atoi standard package parses a string and gives back an integer.
		parsedLimit, err := strconv.Atoi(cmd.UserArgs[0])
		if err != nil {
			return fmt.Errorf("invalid limit: %w", err)
		}
		limit = parsedLimit
	}

	posts, err := appStatePtr.databasePointer.GetPostsForUser(context.Background(), database.GetPostsForUserParams{
		UserID: user.ID,
		// GetPostsForUserParams.Limit field is generated by sqlc as int32 specifically,
		// because Postgres's integer column type maps to a 32-bit integer in Go. So you have:
		// limit (variable above) — type int from strconv.Atoi
		// Limit field — type int32
		Limit: int32(limit),
		//*********************************************************************************************
	})
	if err != nil {
		return err
	}

	for _, post := range posts {
		fmt.Println("Title:", post.Title)
		fmt.Println("URL:", post.Url)
		fmt.Println("Published:", post.PublishedAt)
		fmt.Println("---")
	}
	return nil
}
